homeassistant:
  name: Cozy Home
  latitude: 50.8795389
  longitude: 5.9208255
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/Amsterdam
  elevation: 455
  language: en
  country: NL
  currency: EUR
  packages: !include_dir_named packages
  # allowlist_external_dirs:
  #   - /media
default_config:
media_source:

frontend: !include_dir_merge_named impl/frontend.yaml
lovelace: !include_dir_merge_named impl/lovelace.yaml
group: !include_dir_merge_named impl/groups
person:  !include_dir_merge_named impl/persons.yaml
scene: !include_dir_merge_named impl/scenes.yaml
zone: !include groups/zones.yaml
script: !include_dir_merge_named impl/scripts/
sensor: !include_dir_merge_named impl/sensors
light: !include_dir_merge_named impl/lights.yaml
blueprint: !include_dir_merge_named impl/blueprints/
automation: !include_dir_merge_named impl/automations
