homeassistant:
  name: Cozy Home
  latitude: 50.8795389
  longitude: 5.9208255
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/Amsterdam
  elevation: 455
  language: en
  country: NL
  currency: EUR
  packages: !include_dir_named packages

# Loads default set of integrations. Do not remove.
default_config:

media_source:

# Automations
automation: !include_dir_merge_list automations

# Scripts
script: !include_dir_merge_named scripts/
group: !include_dir_merge_named groups
sensor: !include_dir_merge_list sensors
scene: !include scenes.yaml
light: !include groups/lights.yaml
zone: !include zones.yaml

# Themes
frontend:
  themes: !include_dir_merge_named themes/

# Blueprints
blueprint: !include_dir_named blueprints/
