# views:
#   # - title: overview
#   #   icon: mdi:floor-plan
#   #   cards:
#   #     - type: weather-forecast
#   #       entity: weather.buienradar
#   #       secondary_info_attribute: temperature
#   #       name: Home
#   - !include views/home-view.yaml
#
#views:
#  - title: Home test
#    sections:
#      - type: grid
#        cards:
#          - show_current: true
#            show_forecast: true
#            type: weather-forecast
#            entity: weather.buienradar
#            forecast_type: daily
#            name: Forecast Cozy Home
views:
  - title: Home test
    sections:
      - type: grid
        cards:
          - show_current: true
            show_forecast: true
            type: weather-forecast
            entity: weather.buienradar
            forecast_type: daily
            name: Forecast Cozy Home

  # Main Cards Section
  - cards:
      - type: weather-forecast
        entity: weather.buienradar
        name: Forecast Cozy Home

      - type: custom:auto-entities
        card:
          type: horizontal-stack
        filter:
          include:
            - entity_id: /^person_resident_.*/  # Regex for person entities
        card_options:
          type: custom:button-card
        card:
          type: custom:button-card
          entity: this.entity
          name: >
            {{ state_attr(config.entity, 'name') }}
          styles:
            card:
              - background-image: >
                  url("/local/images/{{ config.entity.split('_')[2] }}.jpg")
              - height: 150px
              - width: 150px
            custom_fields:
              role: >
                Role: {{ state_attr(config.entity, 'role') }}
              trackers: >
                Trackers: {{ state_attr(config.entity, 'trackers') | join(', ') }}

      - type: markdown
        content: >-
          Who - type (family, owner, guest, client, unknown) - doing
          (walking to, sitting) - where
        title: Occupancy

      - type: markdown
        content: >-
          Turned on devices: Lamps, PCs, Fans, Washer, Dryer, Vacuum, TVs,
          Media
        title: Turned on

      - type: heading
        icon: mdi:fridge
        heading: Media
        heading_style: title

      - type: grid
        cards:
          - type: horizontal-stack
            cards:
              - type: markdown
                content: status home (sleep, away, on holiday, present)
              - type: markdown
                content: |-
                  Important messages, like:
                  - Tomorrow: trash
                  - Weather change
                  - Files, P2000 alerts
              - type: markdown
                content: Energy, water, major users
              - type: markdown
                content: |-
                  Doors open
                  Motion detected
            grid_options:
              columns: full

          - type: markdown
            content: Doorbell (conditional)
            grid_options:
              columns: full

          - type: grid
            square: true
            cards:
              - alert_classes:
                  - motion
                  - moisture
                sensor_classes:
                  - temperature
                  - humidity
                type: area
                area: living_room
              - alert_classes:
                  - motion
                  - moisture
                sensor_classes:
                  - temperature
                  - humidity
                type: area
                area: dining_room
              - alert_classes:
                  - motion
                  - moisture
                sensor_classes:
                  - temperature
                  - humidity
                type: area
                area: kitchen
              - alert_classes:
                  - motion
                  - moisture
                sensor_classes:
                  - temperature
                  - humidity
                type: area
                area: office
              - alert_classes:
                  - motion
                  - moisture
                sensor_classes:
                  - temperature
                  - humidity
                type: area
                area: bedroom
              - alert_classes:
                  - motion
                  - moisture
                sensor_classes:
                  - temperature
                  - humidity
                type: area
                area: hall
              - type: area
                area: backyard
              - alert_classes:
                  - motion
                  - moisture
                sensor_classes:
                  - temperature
                  - humidity
                type: area
                area: entrance
              - alert_classes:
                  - motion
                  - moisture
                sensor_classes:
                  - temperature
                  - humidity
                type: area
                area: front_yard
              - alert_classes:
                  - motion
                  - moisture
                sensor_classes:
                  - temperature
                  - humidity
                type: area
                area: laundry_room
            columns: 2
            grid_options:
              columns: full

          - type: grid
            cards:
              - type: markdown
                content: |-
                  - Temp / humidity in top; click temp to view heating popup
                  - Armed/disarmed in top; click to change
                  - Scene in top; click to change
                  - Energy usage in top
                  - Water usage in top
                  - Air quality in top
                  - Lock status in top
              - camera_view: auto
                type: picture-glance
                title: Front (Cam yard, Cam entrance, Cam doorbell)
                image: https://demo.home-assistant.io/stub_config/kitchen.png
                entities:
                  - sensor.sun_next_dawn
                  - sensor.sun_next_dusk
    badges:
      - type: entity
        entity: alarm_control_panel.home_alarm
      - type: entity
        entity: weather.buienradar
      - type: entity
        entity: zone.home
