- name: Ensure .ssh directory exists on control machine
  ansible.builtin.file:
    path: "~/.ssh"
    state: directory
    mode: '0700'

- name: Generate SSH key pair
  community.crypto.openssh_keypair:
    path: "~/.ssh/home_assistant_key"
    size: 4096
    type: rsa
    mode: '0600'
  register: ssh_keypair

- name: Display public key location
  debug:
    msg: "Public key generated at: {{ ssh_keypair.filename }}.pub"

- name: Ensure authorized_keys file exists on Home Assistant
  ansible.builtin.file:
    path: "/config/.ssh/authorized_keys"
    state: touch
    mode: '0600'

- name: Add SSH public key to authorized_keys
  ansible.builtin.lineinfile:
    path: "/config/.ssh/authorized_keys"
    line: "{{ lookup('file', '~/.ssh/home_assistant_key.pub') }}"
    state: present
    create: yes