- name: Movie Night
  entities:
    light.tv_back_light: "on"
    light.ceiling:
      state: "on"
      xy_color: [0.33, 0.66]
      brightness: 200
- name: Evening
  entities:
    light.tv_back_light:
      state: "on"
      brightness: 125
    light.ceiling: off
    media_player.sony_bravia_tv:
      state: "on"
      source: HDMI 1

# scene:
#  - id: '1707342066053'
#    name: Movie nights
#    entities:
#      media_player.kitchen_speaker:
#        device_class: speaker
#        friendly_name: Kitchen speaker
#        supported_features: 152461
#        state: 'off'
#      tts.google_en_com:
#        friendly_name: Google en com
#        state: unknown
#    icon: mdi:popcorn
#    metadata:
#      tts.google_en_com:
#        entity_only: true
