mqtt:
  enabled: true
  host: homeassistant.local
  user: !secret mqtt_user
  password: !secret mqtt_password

detectors:
  coral:
    type: edgetpu
    device: usb

cameras:
  front_yard:
    ffmpeg:
      inputs:
        - path: rtsps://10.69.1.1:7441/gOzQT6MsYY3X8GIU?enableSrtp
          roles:
            - detect
            - rtmp
    width: 1920
    height: 1080
    fps: 5
