# mqtt
mqtt_user: null
mqtt_password: null

# Unifi
unifi_host: null
unifi_username: null
unifi_password: null

# Nest termo
nest_project_id: null
google_project_id: null
google_client_id: null
google_client_secret: null

# Withings
withings_client_id: null
withings_secret: null
