# File: automations/lights_automation.yaml
- alias: Turn on Kitchen Lights at Sunset
  trigger:
    - platform: sun
      event: sunset
  action:
    - service: light.turn_on
      target:
        entity_id: light.kitchen_spots
      data:
        brightness: 200
        color_name: "warm_white"

- alias: Turn off All Lights at Midnight
  trigger:
    - platform: time
      at: "00:00:00"
  action:
    - service: light.turn_off
      target:
        entity_id:
          - light.kitchen_spots
          - light.dining_room_spots
          - light.living_room_spots

- alias: Turn on Kitchen Lights via MQTT
  trigger:
    - platform: sun
      event: sunset
  action:
    - service: mqtt.publish
      data:
        topic: "home/kitchen/lights/command"
        payload: "ON"

- alias: Turn off All Lights via MQTT
  trigger:
    - platform: time
      at: "00:00:00"
  action:
    - service: mqtt.publish
      data:
        topic: "home/all/lights/command"
        payload: "OFF"