input_boolean:
  medicine:
    name: Medicine Reminder
    initial: off
    icon: mdi:tablet

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'

counter:
  my_custom_counter:
    initial: 30
    step: 1