input_boolean:
  medicine:
    name: Medicine Reminder
    initial: off
    icon: mdi:tablet

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
input_select:
  who_cooks:
    name: Who cooks today
    options:
      - Paulus
      - Anne Therese
    initial: Anne Therese
    icon: mdi:panda
  living_room_preset:
    options:
      - Visitors
      - Visitors with kids
      - Home Alone

counter:
  my_custom_counter:
    initial: 30
    step: 1


template:
  - sensor:
      - name: "John Presence"
        state: >
          {% if is_state('binary_sensor.john_detected', 'on') %}
            Home
          {% else %}
            Away
          {% endif %}
        attributes:
          last_seen: >
            {{ states.binary_sensor.john_detected.last_changed | as_timestamp | timestamp_local }}
          current_room: >
            {% if is_state('binary_sensor.john_in_living_room', 'on') %}
              Living Room
            {% elif is_state('binary_sensor.john_in_kitchen', 'on') %}
              Kitchen
            {% else %}
              Unknown
            {% endif %}
          mood: "Happy"  # Static for now; can be dynamic